---
title: "CBASS ED50 analysis"
output: html_document
date: "2023-11-20"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load libraries and custom functions
```{r}
library(drc)
library(quantreg)
library(mcr)
library(broom)
library(lubridate)
library(tidyverse)

# Create custom ggplot theme
theme_custom <- function() {
  theme_bw(base_size = 10, base_family = "Arial") %+replace%
    theme(
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      panel.border = element_rect(color = "black", fill = NA),
      legend.background = element_rect(fill = NA, colour = NA),
      axis.title = element_text(size = 10),
      axis.text = element_text(size = 7)
    )
}

# Function to pivot IPAM data to long form with column for AOI
ipam_convert <- function(data) {
  data %>% select_if(~ !any(is.na(.))) %>%
  pivot_longer(cols = starts_with("f") | starts_with("y")) %>%
  separate(name, into = c("var", "aoi"), sep = "(?<=[A-Za-z_])(?=[0-9])")
}
```

# Plot temperature profiles

### CBASS experiment profiles
```{r}
# Read in CBASS temperature logs and filter for just December 4th run
cbasslogs <- list("data/CBASS_logs/port/LOG.TXT",
                  "data/CBASS_logs/starboard/LOG.TXT")

cbasstemps <- map_dfr(cbasslogs, read_csv) %>%
  # Remove internal header rows
  filter(PrintDate != "PrintDate") %>%
  # Format date and time
  mutate(date = as_date(Date, format = "%Y_%m_%d")) %>%
  unite(time, Th, Tm, Ts, sep = ":") %>%
  unite(dttm, date, time) %>%
  mutate(dttm = ymd_hms(dttm)) %>%
  filter(dttm >= "2023-06-20") %>%
  select(dttm, ShortUniqueID, T1SP, TempT1, T2SP, TempT2, T3SP, TempT3, T4SP, TempT4) %>%
  # Pivot to long format
  pivot_longer(starts_with("T"), names_to = "key", values_to = "temp") %>%
  # Remove rows where temp sensors gave error codes
  filter(temp > 0, temp < 50) %>%
  # Parse tanks, setpoints, and actual temps
  mutate(probe = str_extract(key, "T[0-9]"),
         key = case_when(grepl("SP", key) ~ str_sub(key, 3, 4),
                         TRUE ~ str_sub(key, 1, 4)),
         key = tolower(key)) %>%
  # Filter to only get one temperature reading per second by averaging
  group_by(dttm, ShortUniqueID, probe, key) %>%
  summarize(temp = mean(as.numeric(temp), na.rm = TRUE)) %>%
  ungroup() %>%
  # Create columns for set point and actual temperature
  pivot_wider(names_from = key, values_from = temp) %>%
  # Tidy column types
  mutate(probe = factor(probe)) %>%
  # Add maximum setpoint temperature as max_temp column
  group_by(ShortUniqueID, probe) %>%
  mutate(max_temp = factor(max(sp, na.rm = TRUE))) %>%
  ungroup()

cbasstempsthin <- cbasstemps %>%
  group_by(max_temp) %>%
  slice(which(row_number() %% 3 == 1)) %>%
  ungroup()

cbasstempsfig <- ggplot(cbasstemps, aes(x = dttm, y = temp, group = max_temp)) +
  geom_line(lwd = 0.5, alpha = 1) +
  theme_custom() +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(26.9, 38.2), breaks = seq(27, 38, 1)) +
  labs(x = "Time", y = "Temperature (°C)"); cbasstempsfig

#ggsave(cbasstempsfig, filename = "output/cbass_temps.png", width = 60, height = 80, units = "mm")
```

# -------------

# CBASS results

### Import rack, temperature, and coral position information
```{r}
# Import CBASS metadata (positions of corals on racks, and CBASS temperatures of each rack)
rack_map <- readxl::read_xlsx("RackMaps.xlsx", sheet = "long") %>%
  mutate(date = as_date(as.character(dateCBASS))) %>%
  select(uniquePosition, date, CBASSrun, rack_color = rack.col, position = rack.position, fieldTag)
```

### Import I-PAM data from CBASS
```{r}
# Import PAM data
# And do some things in parallel...
library(furrr)
plan(multisession, workers = 8)

# List all PAM files
pamfiles <- list.files(path = "data/IPAM", pattern = "\\d+_\\d+_.*.csv", 
                       recursive = TRUE, full.names = TRUE)

# Import data from each file
pam1 <- pamfiles %>%
  map_dfr(read_delim, delim = ";", .id = "file_id") %>%
  janitor::clean_names() %>%
  mutate(file_id = basename(pamfiles[as.numeric(file_id)]),
         date = as_date(date, format = "%d.%m.%y"))

# # For files that have multiple sat pulses -- keep the last one only (highest "no." column)
pam2 <- pam1 %>%
  group_by(file_id, date) %>%
  filter(no == max(no)) %>%
  slice_head(n = 1) %>%     # for duplicated file_id/date (data read in multiple times)
  ungroup()

# For each source file, convert to long form data with F, FM, and YII for each AOI
pam3 <- pam2 %>%
  nest(-file_id, -date) %>%
  mutate(data2 = future_map(data, ipam_convert)) %>%
  unnest(data2) %>%
  group_by(file_id, date) %>%
  select(file_id, date, time, aoi, var, value)

# Get rack temp/color info from file_id
pam4 <- pam3 %>%
  separate(file_id, into = c("rack_no", "max_temp", "rack_color"))

# Get "position" of each coral based on aoi -- assuming only one aoi per coral in order
pam5 <- pam4 %>%
  group_by(rack_no, date) %>%
  mutate(position = as.numeric(aoi)) %>%
  ungroup()

# Join PAM data with rack order information (which PAM file corresponds to which rack of corals)
pam <- left_join(rack_map, pam5, by = c("date", "rack_color", "position"))

# # Double-check: should be 1 measurements of Fv/Fm per genet per temperature
# pam %>%
#   filter(var == "y_ii_") %>%
#   count(fieldTag, max_temp) %>%
#   arrange(-n)
# ## great, all have 1 meas.

# Filter only DRTO Acer
pam <- pam %>%
  filter(str_detect(fieldTag, "^B.*"))
```

### Fit dose-response curves
```{r}
# Get Fv/Fm data and tidy
df <- pam %>%
  pivot_wider(names_from = var, values_from = value) %>%
  mutate(fvfmraw = y_ii_, fvfm = y_ii_,
         max_temp = as.numeric(max_temp)) %>%
  select(date, fieldTag, max_temp, f, fm, fvfmraw, fvfm)

# Define function to fit 3-parameter LL model to data and return NULL if fitting error
ll3 <- function(data) {
  drm(fvfm ~ max_temp, data = data, 
      fct = LL.3(names = c("hill", "max", "ED50")))}#,
      # upperl = c(50, 0.7, 40),
      # lowerl = c(20, 0.3, 30))}
tryll3 <- possibly(ll3, otherwise = NULL)

# Fit model to each coral, get parameters, fitted values, and residuals
initmods <- df %>%
  nest(data = c(date, max_temp, f, fm, fvfmraw, fvfm)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
ed50 <- initmods %>% 
  select(fieldTag, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# hist(ed50$estimate, breaks = 30)
mean(ed50$estimate)

# Collect raw data, fitted values, and diagnostics
vals <- initmods %>%
  select(fieldTag, pred) %>%
  unnest(pred) %>%
  full_join(ed50) %>%
  full_join(df) %>%
  rename(ed50 = estimate) %>%
  mutate(problem = "none")
```

### Filter outliers
```{r drc_diagnostics}
# # Identify problematic data points based on cook's distance and residuals
counts <- vals %>%
  group_by(fieldTag) %>%
  summarise(n = sum(!is.na(fvfm)))
dff <- vals %>%
  left_join(counts) %>%
  group_by(fieldTag) %>%
  mutate(cooksd.thresh = 4/n) %>%   # Calculate cook's distance threshold as 4/n
  mutate(max_to_remove = floor(n * 0.15)) %>%
  ungroup() %>%
  mutate(problem = case_when(.cooksd > cooksd.thresh ~ "high cook's distance",
                             abs(.resid) > 0.5 ~ "high residual",
                             TRUE ~ "none")) %>%
  group_by(fieldTag, outlier = problem %in% c("high cook's distance", "high residual")) %>%
  mutate(n.outliers = n(),
         rank.out = order(.cooksd, decreasing = TRUE)) %>%
  ungroup() %>%
  mutate(fvfm = case_when(outlier & rank.out <= max_to_remove ~ NA_real_,
                          TRUE ~ fvfmraw))

# Refit models without problematic points
fmods <- dff %>%
  select(fieldTag, max_temp, f, fm, fvfmraw, problem, fvfm) %>%
  nest(data = c(max_temp, f, fm, fvfmraw, fvfm, problem)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
fed50 <- fmods %>%
  select(fieldTag, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Collect raw data, fitted values, and ed50 estimates
fvals <- fmods %>%
  select(fieldTag, pred) %>%
  unnest(pred) %>%
  full_join(fed50) %>%
  full_join(select(dff, fieldTag, max_temp, f, fm, fvfmraw, problem, fvfm)) %>%
  rename(ed50 = estimate)
```

### Plot dose response curves for each genotype
```{r plot, fig.width = 10, fig.height = 10}
# ed50 <- ed50 %>%
#   mutate(geno = factor(tag_no))

vals <- vals %>%
  mutate(fieldTag = fct_reorder(factor(fieldTag), ed50, .fun = mean))
fvals <- fvals %>%
  mutate(fieldTag = fct_reorder(factor(fieldTag), ed50, .fun = mean, na.rm = TRUE))

# Get finer scale fitted values for plotting
pred <- initmods %>%
  mutate(pred = map(ll3, ~augment(.x, newdata = data.frame(max_temp = seq(28.5, 40, 0.001))))) %>%
  select(fieldTag, pred) %>%
  unnest(pred) %>%
  mutate(fieldTag = factor(fieldTag))
fpred <- fmods %>%
  mutate(pred = map(ll3, ~augment(.x, newdata = data.frame(max_temp = seq(28.5, 40, 0.001))))) %>%
  select(fieldTag, pred) %>%
  unnest(pred) %>%
  mutate(fieldTag = factor(fieldTag))

# Plot all drc's on separately
alldrc <- ggplot(fvals, aes(x = max_temp, y = fvfm)) +
  facet_wrap(~fieldTag) +
  geom_point(pch = 1) +
  geom_point(pch = 4, data = vals) +
  geom_line(aes(y = .fitted), data = fpred) +
  geom_line(aes(y = .fitted), data = pred, lty = 2) +
  geom_vline(aes(xintercept = estimate), data = fed50, lty = 1, lwd = 0.1) +
  geom_vline(aes(xintercept = estimate), data = ed50, lty = 2, lwd = 0.1) +
  geom_text(aes(x = estimate, y = 0.05, label = round(estimate, 2)), data = fed50,
            size = 2, nudge_x = -1.5) +
  #scale_shape_manual(values = c(4, 1)) +
  xlim(30, 38) +
  theme_custom() +
  theme(legend.position = "none", strip.text = element_text(size = 2)) +
  labs(x = "Temperature (°C)", y = "Fv/Fm"); alldrc

#ggsave(alldrc, filename = "output/FigureS1.png", width = 183, height = 183, units = "mm")

# Plot all curves together
drcs <- ggplot(pred, aes(x = max_temp, y = .fitted, group = fieldTag)) +
  geom_line(alpha = 0.7, lwd = 0.25) +
  scale_x_continuous(limits = c(32, 38), expand = c(0, 0)) +
  theme_custom() +
  theme(legend.position = "none"); drcs

# Histogram of ED50s
left_join(ed50, rack_map) %>%
  ggplot(aes(x = estimate, fill = factor(date))) +
  geom_histogram(alpha = 0.5, position = "stack", breaks = seq(32,38.5,0.25)) +
  scale_x_continuous(limits = c(32, 38), expand = c(0, 0)) +
  theme_custom()

# Test for difference among dates
resdf <- left_join(ed50, rack_map)
mod <- lm(estimate ~ factor(date), data = resdf)
anova(mod)

# Use initmods for now (not filtered). Only one AOI per coral, so can't afford to lose any datapoints. Filter out some poor fits based on initmods or when n < 8 (need to go back and check why we are missing data for these).
goods <- initmods %>%
  mutate(n = map_dbl(data, nrow)) %>%
  filter(n > 5) %>%
  pull(fieldTag)

ed50ss <- ed50 %>%
  filter(fieldTag %in% goods) %>%
  left_join(rack_map)

# Histogram of Filtered ED50s
ggplot(ed50ss, aes(x = estimate, fill = factor(date))) +
  geom_histogram(alpha = 0.5, position = "stack", breaks = seq(32,38.5,0.25)) +
  scale_x_continuous(limits = c(32, 38), expand = c(0, 0)) +
  theme_custom()
```

### Import collection information
```{r}
md <- readxl::read_xlsx("Collections.xlsx", sheet = "CollectionNotes") %>%
  select(fieldTag, dateCollected, site, depth_ft)

res <- left_join(ed50ss, md)


# Does ED50 vary across depth?
ggplot(res, aes(x = depth_ft, y = estimate)) +
  geom_point(aes(color = factor(date))) +
  geom_smooth(method = "lm")

mod <- lm(estimate ~ depth_ft, data = res)
anova(mod)

date_means <- res %>%
  group_by(date) %>%
  summarize(mean = mean(estimate),
            sd = sd(estimate))

# Does ED50 vary among sites?
ggplot(res, aes(x = site, y = estimate, group = date)) +
  facet_grid(~date, scales = "free_x") +
  geom_hline(aes(yintercept = mean), data = date_means) +
  geom_rect(aes(ymax = mean + sd, ymin = mean - sd), xmin = 0, xmax = 10, 
              data = date_means, alpha = 0.3, inherit.aes = FALSE) +
  #geom_boxplot() +
  geom_jitter(alpha = 0.7, width = 0.15) +
  theme(axis.text.x = element_text(angle = 90))

mod <- lm(estimate ~ depth_ft, data = res)
anova(mod)
```

